name: test container action
on: [push]
jobs:
  Test-Job:
    runs-on:
      - codebuild-Case175928201000066GitHubActionsRunner-${{ github.run_id }}-${{ github.run_attempt }}
    strategy:
      matrix:
        repeat: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15]  # 15回繰り返し
    steps:
      - name: Pull ECR Public image to test rate limit
        run: |
          docker pull public.ecr.aws/docker/library/alpine:3.18
          echo "Pulled image count ${{ matrix.repeat }}"
