name: test container action
on: [push]
jobs:
 daily_job:
   runs-on:
    - codebuild-Case175928201000066GitHubActionsRunner-${{ github.run_id }}-${{ github.run_attempt }}
 your_github_secrets_environment
    steps:
      - uses: actions/checkout@v3
      - name: Run local Docker container action
        uses: ./  # このリポジトリ内のカスタムアクションを呼び出す 
