name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-Case175928201000066GitHubActionsRunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
